### ISSUE TITLE
Adding a paper

### ISSUE THREAD

**Issue by mkimhi** [BBBBchan/Awesome-Semi-Supervised-Semantic-Segmentation#4]
Hi,
Could you add the paper "Semi-Supervised Semantic Segmentation via Marginal Contextual Information" from 2023 on arxiv?
https://arxiv.org/abs/2308.13900

It also apear on paperswithcode
https://paperswithcode.com/paper/semi-supervised-semantic-segmentation-via-3

**Comment by BBBBchan** [comment]
Thank you for your attention! We have added the paper you mentioned to the list.
