### ISSUE TITLE
Adding a paper

### ISSUE THREAD

**Issue by mai556** [BBBBchan/Awesome-Semi-Supervised-Semantic-Segmentation#5]
Hi,
Could you add our paper "[RankMatch: Exploring the Better Consistency Regularization for Semi-supervised Semantic Segmentation](https://openaccess.thecvf.com/content/CVPR2024/papers/Mai_RankMatch_Exploring_the_Better_Consistency_Regularization_for_Semi-supervised_Semantic_Segmentation_CVPR_2024_paper.pdf)" on CVPR2024? 
This is the code repository [https://github.com/mai556/RankMatch](https://github.com/mai556/RankMatch)

**Comment by BBBBchan** [comment]
Sure! We have added the paper you mentioned to the list.
