### ISSUE TITLE
Adding a paper

### ISSUE THREAD

**Issue by Hugo-cell111** [BBBBchan/Awesome-Semi-Supervised-Semantic-Segmentation#6]
Hi! I have just found a paper accepted by ICCV23 named "Locating Noise is Halfway Denoising for Semi-Supervised Segmentation", you might add it to the list~

**Comment by BBBBchan** [comment]
Thanks for your advice! I have added it into the list.

**Comment by Hugo-cell111** [comment]
Sinkhorn Output Perturbations: Structured Pseudo-Label Noise in Semi-Supervised Segmentation. Also a recommended paper~
