### ISSUE TITLE
Adding a paper

### ISSUE THREAD

**Issue by krumo** [BBBBchan/Awesome-Semi-Supervised-Semantic-Segmentation#7]
Hi! Could you consider to add CVPR 2024 paper [Training Vision Transformers for Semi-Supervised Semantic Segmentation](https://openaccess.thecvf.com/content/CVPR2024/papers/Hu_Training_Vision_Transformers_for_Semi-Supervised_Semantic_Segmentation_CVPR_2024_paper.pdf) to the list? 

Thanks for maintaining such a great repo!

**Comment by BBBBchan** [comment]
Sure! I have added it into the list.
