### ISSUE TITLE
Adding some papers

### ISSUE THREAD

**Issue by Hugo-cell111** [BBBBchan/Awesome-Semi-Supervised-Semantic-Segmentation#8]
Hi! I have just found some papers related to S4, maybe you could add them to the paper list~
Sinkhorn Output Perturbations: Structured Pseudo-Label Noise in Semi-Supervised Segmentation. 
CFCG: Semi-Supervised Semantic Segmentation via Cross-Fusion and Contour Guidance Supervision, ICCV23
Interactive Network Perturbation between Teacher and Students for Semi-Supervised Semantic Segmentation, WACV24
SemiCVT: Semi-Supervised Convolutional Vision Transformer for Semantic Segmentation, CVPR23
Diverse Cotraining Makes Strong Semi-Supervised Segmentor， ICCV23
Logic-induced diagnostic reasoning for semi-supervised semantic segmentation, ICCV23

**Comment by BBBBchan** [comment]
Thank you so much for your valuable contributions to this repository. I've  added the majority of the papers to our list, with the exception of the first one.

In the case of the paper titled "Sinkhorn Output Perturbations: Structured Pseudo-Label Noise in Semi-Supervised Segmentation," I've noticed that it's currently accessible only via OpenReview, as it was a submission for ICLR 2024, and, regrettably, it was not accepted. Given that the authors have not made a preprint available on arXiv, we've decided to hold off on including this particular paper in our list for now. We will certainly add it once an arXiv version is released, or should the paper be accepted, or if we receive a direct inquiry from one of the authors.

Once again, I sincerely appreciate your efforts and contributions!
