### ISSUE TITLE
Add a paper

### ISSUE THREAD

**Issue by Hugo-cell111** [BBBBchan/Awesome-Semi-Supervised-Semantic-Segmentation#9]
Hi! A paper named Uncertainty-Participation Context Consistency Learning for Semi-supervised Semantic Segmentation could be added to the list~ accepted by ICASSP25

**Comment by BBBBchan** [comment]
Hi there. This paper has already been added to the list earlier today.  Thank you for your reminder; I have changed the publication from ICASSP 2024 to ICASSP 2025.
